In [ ]:
import numpy as np
import time

In [ ]:
#comparison between py list and np arrays
size = 10_000_000

#py list 
start = time.time()
py_list = list(range(size))
sq = [x**2 for x in py_list]
end = time.time()

print(f"Python list time {end -start} second")

#np array

start = time.time()
np_arr = np.arange(size)

#vectorization
sq_arr = np_arr ** 2
end = time.time()
print(f"NumPY Array time {end -start} second")

In [ ]:
#memory 
import sys
print(f"py list size {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"np array size {sys.getsizeof(np_arr.nbytes)} bytes")


NumPy Arrays

In [ ]:
# Array Creation metheods 
arr = np.zeros(3)
print(arr)

arr2 = np.ones(4) #row as attribute 
print(arr2)

arr3 = np.full((3,3) , 10)
print(arr3)

arr4= np.eye(5)
print(arr4)

arr5 = np.arange(1,11,2)
print(arr5)

arr6 = np.linspace(1,100,4)
print(arr6)


In [ ]:
# Array Properties

arr = np.array([[1,2,3,4],[5,6,7,8]]) #shap - dimension = row x col
print(arr.shape) #dimensions - (m x n)
print(arr.size) #total element = m*n
print(arr.dtype) # data type object
print(arr.ndim)# dimension

float_array = arr.astype(np.float64) #typCasting 
print(float_array,float_array.dtype)


Array Operator

In [ ]:
#Reshaping 
arr = np.array([[1,2,3],[4,5,6]])
print(arr, "and" ,arr.shape)
reshaped = np.reshape(arr,(3,2))
print(reshaped,"and", reshaped.shape)

[[1 2 3]
 [4 5 6]] and (2, 3)
[[1 2]
 [3 4]
 [5 6]] and (3, 2)
